version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks:
      - todo

  mysql:
    container_name: mysql
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - todo

networks:
  todo:
    driver: bridge
